### ISSUE TITLE
virustotal.py does not fail gracefully

### ISSUE THREAD

**Issue by Rich5** [ChrisTruncer/Just-Metadata#17]
Grabbing list of TOR exit nodes..
Grabbing attacker IP list from the Animus project...
Grabbing EmergingThreats list...
Grabbing AlienVault reputation list...
Grabbing Blocklist.de info...
Grabbing DragonResearch's SSH list...
Grabbing DragonResearch's VNC list...
Grabbing NoThinkMalware list...
Grabbing NoThinkSSH list...
Grabbing Feodo list...
Grabbing antispam spam list...
Grabbing malc0de list...
Grabbing MalwareBytes list...
[_] Error: You didn't provide a MyWOT API Key!
[_] Please edit the MyWOT module and add in your API Key.
[_] Create an account at www.mywot.com and get a free API key.
Traceback (most recent call last):
  File "JustMetadata.py", line 94, in <module>
    the_conductor.menu_system()
  File "/root/Tools/Just-MetaData/common/orchestra.py", line 226, in menu_system
    self.user_command.split()[1])
  File "/root/Tools/Just-MetaData/common/orchestra.py", line 340, in run_gather_command
    ig_obj.gather(self.system_objects)
*_  **File "modules/intelgathering/virustotal.py", line 73, in gather
    json_response = json.loads(response)****
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ChrisTruncer** [comment]
Thanks for the report, missed that. I'll get it fixed!

**Comment by Rich5** [comment]
Sure thing. Just playing around with the tool :)

**Comment by ChrisTruncer** [comment]
This should now be fixed.  Thanks for letting me know again!

**Comment by Rich5** [comment]
Just pulled the latest. Similar error. Different line.

Grabbing Feodo list...
Grabbing antispam spam list...
Grabbing malc0de list...
Grabbing MalwareBytes list...
Traceback (most recent call last):
  File "JustMetadata.py", line 94, in <module>
    the_conductor.menu_system()
  File "/root/Tools/Just-Metadata/common/orchestra.py", line 226, in menu_system
    self.user_command.split()[1])
  File "/root/Tools/Just-Metadata/common/orchestra.py", line 340, in run_gather_command
    ig_obj.gather(self.system_objects)
  File "modules/intelgathering/virustotal.py", line 54, in gather
    json_response = json.loads(response)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ChrisTruncer** [comment]
Ah, I only put the fix in the domain lookup area.  It should now contain it for both the domain and IP lookup, so it SHOULD now be fixed (fingers crossed).

Thanks again!

**Comment by Rich5** [comment]
Confirmed. Thanks for the great response time! Got another one incoming though sorry
