### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xsallowed** [ChrisTruncer/Just-Metadata#34]
I am getting following error. Are there any pre-requisite modules that i need to install before running just-metadat.

Traceback (most recent call last):
  File "./JustMetadata.py", line 93, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/home/tahir/Just-Metadata/common/orchestra.py", line 67, in **init**
    self.load_intelgathering_functions()
  File "/home/tahir/Just-Metadata/common/orchestra.py", line 179, in load_intelgathering_functions
    name.replace("/", ".").rstrip('.py'), name)
  File "modules/intelgathering/whois_info.py", line 6, in <module>
    from ipwhois.exceptions import IPDefinedError
ImportError: No module named ipwhois.exceptions

**Comment by ChrisTruncer** [comment]
Yes,

There is a setup script, please either run that or install those
dependencies manually.

The ReadMe also tells you exactly what you need to do.

---

Christopher Truncer
@christruncer http://www.twitter.com/christruncer

On September 19, 2016 at 2:13:46 PM, xsallowed (notifications@github.com)
wrote:

I am getting following error. Are there any pre-requisite modules that i
need to install before running just-metadat.

Traceback (most recent call last):
File "./JustMetadata.py", line 93, in
the_conductor = orchestra.Conductor(args)
File "/home/tahir/Just-Metadata/common/orchestra.py", line 67, in _init_
self.load_intelgathering_functions()
File "/home/tahir/Just-Metadata/common/orchestra.py", line 179, in
load_intelgathering_functions
name.replace("/", ".").rstrip('.py'), name)
File "modules/intelgathering/whois_info.py", line 6, in
from ipwhois.exceptions import IPDefinedError
ImportError: No module named ipwhois.exceptions

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ChrisTruncer/Just-Metadata/issues/34, or mute the
thread
